version: "3.9"

services:
  app:
    build: .
    container_name: royalplace_app
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    depends_on:
      - redis
    command: pnpm run start   # production mode

  redis:
    image: redis:8
    container_name: royalplace_redis
    ports:
      - "6379:6379"
