version: "3.9"

services:
  app:
    build: .
    container_name: royalplace_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - ./.env
    depends_on:
      - redis
    command: pnpm run dev

  redis:
    image: redis:8
    container_name: royalplace_redis
    ports:
      - "6379:6379"
