version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: royalplace_app
    ports:
      - "5000:5000"               
    env_file:
      - ./.env       
    command: pnpm run start      
    restart: unless-stopped     
