name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build

      # Install Railway CLI
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      # Deploy to Railway (Service ID optional)
      - name: Deploy to Railway
        run: |
          if [ -n "${{ secrets.RAILWAY_SERVICE_ID }}" ]; then
            railway up --service ${{ secrets.RAILWAY_SERVICE_ID }}
          else
            railway up
          fi
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
