name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Cache pnpm dependencies
      - name: Cache pnpm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # 3. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 4. Install pnpm globally
      - name: Install pnpm
        run: npm install -g pnpm

      # 5. Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 6. Build TypeScript project (incremental for faster builds)
      - name: Build project
        run: pnpm run build

      # 7. Install Railway CLI
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      # 8. Deploy to Railway using service ID
      - name: Deploy to Railway
        run: |
          railway up --service ${{ secrets.RAILWAY_SERVICE_ID }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
   